language: python
python:
  - "3.6.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
# command to install dependencies
script:
  - pytest

after success:
  - coveralls